repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
    -   id: gitleaks