apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: dingo-pdssd-extreme
provisioner: pd.csi.storage.gke.io
parameters:
    type: pd-extreme
    csi.storage.k8s.io/fstype: ext4
    replication-type: none
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: dingo-pdssd-extreme-ha
provisioner: pd.csi.storage.gke.io
parameters:
    type: pd-extreme
    csi.storage.k8s.io/fstype: ext4
    replication-type: regional-pd
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: dingo-pdssd
provisioner: pd.csi.storage.gke.io
parameters:
    type: pd-ssd
    csi.storage.k8s.io/fstype: ext4
    replication-type: none
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: dingo-pdssd-ha
provisioner: pd.csi.storage.gke.io
parameters:
    type: pd-ssd
    csi.storage.k8s.io/fstype: ext4
    replication-type: regional-pd
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: dingo-pdssd-balanced
provisioner: pd.csi.storage.gke.io
parameters:
    type: pd-balanced
    csi.storage.k8s.io/fstype: ext4
    replication-type: none
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: dingo-pdssd-balanced-ha
provisioner: pd.csi.storage.gke.io
parameters:
    type: pd-balanced
    csi.storage.k8s.io/fstype: ext4
    replication-type: regional-pd
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: dingo-pdhdd
provisioner: pd.csi.storage.gke.io
parameters:
    type: pd-standard
    csi.storage.k8s.io/fstype: ext4
    replication-type: none
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: dingo-pdhdd-ha
provisioner: pd.csi.storage.gke.io
parameters:
    type: pd-standard
    csi.storage.k8s.io/fstype: ext4
    replication-type: regional-pd
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
