apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
    name: dingo-demo-6
spec:
    version: 6.8.23
    http:
        service:
            spec:
                type: LoadBalancer
    secureSettings:
    - secretName: gcs-credentials
    nodeSets:
    - name: zone-a
      count: 3
      config:
          node.master: true
          node.data: true
          node.ingest: true
          node.ml: true
          xpack.ml.enabled: true
          node.store.allow_mmap: true
          index.store.type: hybridfs
          cluster.routing.allocation.awareness.attributes: zone
          node.attr.zone: us-central1-a
          #cluster.remote.connect: true
          xpack.security.authc.anonymous.roles: monitoring_user
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
            accessModes:
            - ReadWriteOnce
            resources:
                requests:
                    storage: 128Gi
            storageClassName: dingo-pdssd-balanced
      podTemplate:
          metadata:
              labels:
                  ingest: "on"
                  coord: "on"
          spec:
              containers:
              - name: elasticsearch
                resources:
                    requests:
                        memory: 4Gi
                        cpu: 1000m
                    limits:
                        memory: 4Gi
                        cpu: 1000m
                env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx2g"
                - name: PRE_STOP_MAX_WAIT_SECONDS
                  value: "20"
                - name: PRE_STOP_ADDITIONAL_WAIT_SECONDS
                  value: "30"
                - name: READINESS_PROBE_TIMEOUT
                  value: "10"
                readinessProbe:
                    exec:
                        command:
                        - bash
                        - -c
                        - /mnt/elastic-internal/scripts/readiness-probe-script.sh
                    failureThreshold: 3
                    initialDelaySeconds: 10
                    periodSeconds: 12
                    successThreshold: 1
                    timeoutSeconds: 12
              initContainers:
              #- name: sysctl
                 #securityContext:
                     #priviledged: true
                #command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
              - name: install-plugins
                command:
                - sh
                - -c
                - |
                  bin/elasticsearch-plugin install --batch repository-gcs
              nodeSelector:
                  cloud.google.com/gke-nodepool: default-pool
              affinity:
                  podAntiAffinity:
                      preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: 100
                        podAffinityTerm:
                            labelSelector:
                                matchLabels:
                                    elasticsearch.k8s.elastic.co/cluster-name: dingo
                            topologyKey: kubernetes.io/hostname
    
