apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: elasticsearch-sample-snapshotter
spec:
    schedule: "@daily"
    concurrencyPolicy: Forbid
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                    - name: snapshotter
                      image: centos:7
                      volumeMounts:
                      - name: es-basic-auth
                        mountPath: /mnt/elastic/es-basic-auth
                      command:
                      - /bin/bash
                      args:
                      - -c
                      - 'curl -s -i -k -u "elastic:$(</mnt/elastic/es-basic-auth/elastic)" -XPUT "https://elasticsearch-sample-es-http:9200/_snapshot/my_gcs_repository/%3Csnapshot-%7Bnow%2Fd%7D%3E" | tee /dev/stderr | grep "200 OK"'
                    restartPolicy: OnFailure
                    volumes:
                    - name: es-basic-auth
                        secret:
                            secretName: elasticsearch-sample-elastic-user
